export const projects = [
  {
    title: 'Express.js',
    description: "Triage issues and help maintain the Express.js framework.",
      image: '/images/express.jpg',
      tags: ['Express', 'JavaScript', 'Node.js', 'npm'],
    source: 'https://github.com/expressjs/express',
    visit: 'https://expressjs.com/',
    techUsed: "Express, JavaScript, Node.js, npm",
    id: 0,
  },
  {
    title: 'This Website!',
    description: "Developed this website using React.js, Next.js, Material-UI, Styled-Components, and TypeIt.js.",
      image: '/images/this_website.jpg',
      tags: ['React', 'Next', 'Material-UI', 'Styled-Components', 'TypeIt', 'npm', 'Node.js', 'git', 'JavaScript'],
    source: 'https://github.com/import-brain/ericcheng.software',
    visit: 'https://ericcheng.software',
    techUsed: "React, Next, Material-UI, Styled-Components, TypeIt.js",
    id: 1,
  },
  {
    title: 'Elemenpy',
    description: "Wrote a Python module that helps you to execute operations using elements in the periodic table.",
      image: '/images/elemenpy.png',
      tags: ['Python', 'pip', 'pypi'],
    source: 'https://github.com/import-brain/elemenpy',
    visit: 'https://pypi.org/project/elemenpy/',
    techUsed: "Python, pip",
    id: 2,
  },
  {
    title: 'freeCodeCamp',
    description:"Contributed to freeCodeCamp's project curriculum, unit testing, and documentation.",
    image: '/images/freeCodeCamp.png',
    tags: ['React', 'JavaScript', 'TypeScript', 'Jest'],
    source: 'https://github.com/freeCodeCamp/freeCodeCamp',
    visit: 'https://freecodecamp.org',
    techUsed: "TypeScript, JavaScript, React, Jest",
    id: 3,
  },
  {
    title: 'basic_calc',
    description: "Wrote and shipped a small calculator utility using Python that can perform the four basic arithmetic operations, square root, circle area, trig functions, and more.",
    image: '/images/basic_calc.jpg',
    tags: ['Python', 'PyInstaller', 'git'],
    source: 'https://github.com/import-brain/basic_calc',
    visit: 'https://github.com/import-brain/basic_calc',
    techUsed: "Python, PyInstaller",
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];